### ISSUE TITLE
Provide moe human-readable labels for activities

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#10]
**Is your feature request related to a problem? Please describe.**
Currently the labels for the activities are automatically extracted from the keys in the matlabbatch, this is great but could be improved to have more human-readable labels.

**Describe the solution you'd like**
We could add a mapping between the keys in the matlabbatch and a human-readable name/label. This could be stored in a parameter file very similarly to what is done to add inputs to activities.

What do you think?

**Comment by thomasbtnfr** [comment]
I think it's a good idea. Should this mapping also be shared with other software like fsl and afni? In this case, when building the mapping, we should take into account the different software?

We could maybe build an array like this:
| FSL | AFNI | SPM | Name |
| -------- | -------- | -------- | ------- |
| GunZipped Files     | Unzip     | Unzip     | Our mapping    |

**Comment by cmaumet** [comment]
We discussed this on January 9th and agreed on having separate vocabularies for each software packages. The work of harmonizing across software will be done through the ontology (later on).

**Comment by cmaumet** [comment]
This has been solved in https://github.com/bids-standard/BEP028_BIDSprov/pull/84
