### ISSUE TITLE
[Bug]: command cp -r

### ISSUE THREAD

**Issue by thomasbtnfr** [Inria-Empenn/BEP028_BIDSprov#15]
### batch name and line

Example of line : `cp -r /usr/local/packages/fsl-5.0.8/doc/images .files/images` located [here](https://github.com/incf-nidash/nidmresults-examples/blob/master/fsl_con_f_multiple/report_log.html#L15).

### What happened?

I have a doubt about the desired output. Indeed, the `-r` (recursive) option copies one directory into another but what do we expect to get?

Currently, we have this:
```json
      {
        "@id": "urn:351b3990-6953-4085-9e32-413d38973535",
        "label": "feat_main_script_cp",
        "wasAssociatedWith": "urn:c433fb2a-5b6e-4d88-b596-6270fa9a3263",
        "command": "cp -r /usr/local/packages/fsl-5.0.8/doc/images .files/images",
        "attributes": [
          [
            "-r",
            "/usr/local/packages/fsl"  (the rest is missing by the way, this is corrected in the branch `boutiques`)
          ]
        ],
        "used": [
          "urn:162fe375-82fe-4ca1-9fe4-58d7cb95bd65"
        ],
        "prov:wasInfluencedBy": "urn:42e2bb15-639b-45a4-b493-49be04391084"
      }
```

### Describe the expected ground-truth ?

I would expect to see an `r` attribute with no value and two used entities which are directories. After research, it seems possible to calculate checksums on entire directories. What do you think @cmaumet?

```json
      {
        "@id": "urn:dbcad5f7-deb2-4311-9296-213ea6711461",
        "label": "feat_main_script_cp",
        "wasAssociatedWith": "urn:b06c78eb-7bf3-4c3f-a798-b0a8f8956d04",
        "command": "cp -r /usr/local/packages/fsl-5.0.8/doc/images .files/images",
        "attributes": [
        [
          "r"
        ]
        ],
        "used": [
          "urn:67a8a94c-02ec-41f2-8030-75e64f0d3794",
          "urn:139944bb-63b0-4b7e-b44d-e9950c07121d"
        ],
        "prov:wasInfluencedBy": "urn:de2c15c3-3a37-4bcd-ab20-469c87f6cd23"
      }
```

### What soft is concerned

FSL

**Comment by cmaumet** [comment]
@thomasbtnfr, related to #27, for now I would have something like:

```
      {
        "@id": "urn:dbcad5f7-deb2-4311-9296-213ea6711461",
        "label": "feat_main_script_cp",
        "wasAssociatedWith": "urn:b06c78eb-7bf3-4c3f-a798-b0a8f8956d04",
        "command": "cp -r /usr/local/packages/fsl-5.0.8/doc/images .files/images",
        "used": [
          "urn:67a8a94c-02ec-41f2-8030-75e64f0d3794",
          "urn:139944bb-63b0-4b7e-b44d-e9950c07121d"
        ],
      }
```
  where what is inside `used` is defined by a config file for FSL, how do you feel about this?

**Comment by thomasbtnfr** [comment]
Finally, wouldn't it be a single entity used? 
Only one used entity corresponding to `/usr/local/packages/fsl-5.0.8/doc/images` and one entity generatedBy this command corresponding to `.files/images`.

**Comment by cmaumet** [comment]
Yes I agree!

**Comment by thomasbtnfr** [comment]
Fixed with the description file : https://github.com/bids-standard/BEP028_BIDSprov/blob/9744a0eb751e2a742b39878c11db7a8a6b258372/bids_prov/fsl/description_functions.json#L36
Furthermore, the `Feat main script` section is now ignored.
