### ISSUE TITLE
[Bug]: expected output fsl_sub

### ISSUE THREAD

**Issue by thomasbtnfr** [Inria-Empenn/BEP028_BIDSprov#17]
### batch name and line

`/usr/local/packages/fsl-5.0.8/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/packages/fsl-5.0.8/bin/feat /storage/essicd/data/NIDM-Ex/BIDS_Data/RESULTS/TEST/nidmresults-examples/fsl_con_f_multiple_test.feat/design.fsf -D /storage/essicd/data/NIDM-Ex/BIDS_Data/RESULTS/TEST/nidmresults-examples/fsl_con_f_multiple_test.feat -I 1 -init
`

### What happened?

I don't really know what is expected as output for the fsl_sub function. It seems to allow parallelization of tasks.

At the moment it is parsed in this way but it seems incorrect to me:

```json
{
        "@id": "urn:652850d5-35a3-4111-9fe1-eff69559a0a9",
        "label": "feat_main_script_fsl_sub",
        "wasAssociatedWith": "urn:b06c78eb-7bf3-4c3f-a798-b0a8f8956d04",
        "command": "/usr/local/packages/fsl-5.0.8/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/packages/fsl-5.0.8/bin/feat /storage/essicd/data/NIDM-Ex/BIDS_Data/RESULTS/TEST/nidmresults-examples/fsl_con_f_multiple_test.feat/design.fsf -D /storage/essicd/data/NIDM-Ex/BIDS_Data/RESULTS/TEST/nidmresults-examples/fsl_con_f_multiple_test.feat -I 1 -init",
        "attributes": [
          [
            "-T",
            "10"
          ],
          [
            "-l",
            "logs"
          ],
          [
            "-N",
            "feat0_init"
          ],
          [
            "-D",
            "/storage/essicd/data/NIDM"
          ],
          [
            "-I",
            "1"
          ]
        ],
        "used": [
          "urn:e4c7a747-8eae-4635-bc71-7ea7d9e3a626"
        ],
        "prov:wasInfluencedBy": "urn:de2c15c3-3a37-4bcd-ab20-469c87f6cd23"
      }
```

### Describe the expected ground-truth ?

fsl_sub has 4 attributes (T, I and N) and one function (which also has attributes and entities) if I understand correctly. How could we represent it @cmaumet ?

### What soft is concerned

FSL

**Comment by cmaumet** [comment]
@thomasbtnfr: thanks for spotting this! I would be keen to remove/comment-out the `attributes` parameter until we have decided how to handle the parsing of the command line. Would that solve the issue? Or did you identify other problems as well?

**Comment by thomasbtnfr** [comment]
I wonder how we could convert the following command into bids-prov?
`/usr/local/packages/fsl-5.0.8/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/packages/fsl-5.0.8/bin/feat /storage/essicd/data/NIDM-Ex/BIDS_Data/RESULTS/TEST/nidmresults-examples/fsl_con_f_multiple_test.feat/design.fsf -D /storage/essicd/data/NIDM-Ex/BIDS_Data/RESULTS/TEST/nidmresults-examples/fsl_con_f_multiple_test.feat -I 1 -init
31622`

What do you think about the following solution ?
![image](https://user-images.githubusercontent.com/115700860/217545461-d8eddc51-8f05-4e79-be03-d2840f8bbf13.png)

**Comment by cmaumet** [comment]
As discussed on our last meeting with @thomasbtnfr, for now we will ignore the beginning of the FSL log file (up to the `Initialization` heading) are those are higher level commands (that we might model later on).
