### ISSUE TITLE
[Bug]: Command field for FSL

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#18]
### batch name and line

https://github.com/bids-standard/BEP028_BIDSprov/blob/master/results/fsl/nidmresults-examples_fsl_con_f_multiple_report_log.md 

### What happened?

Currently there is no `Command` stored in the FSL Activities, see for example: https://github.com/bids-standard/BEP028_BIDSprov/blob/master/results/fsl/nidmresults-examples_fsl_con_f_multiple_report_log.jsonld#L21-L30

### Describe the expected ground-truth ?

The expected ground-truth : 
`'Command': "/bin/cp /tmp/feat_wYxBhi.fsf design.fsf"`

### What soft is concerned

FSL

**Comment by thomasbtnfr** [comment]
The addition of `Command` (for FSL) has been done in the `boutiques` branch. A PR will be opened soon. 
Here is an [example file](https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/boutiques/results/fsl/nidmresults-examples_fsl_con_f_multiple_report_log.jsonld).
