### ISSUE TITLE
Remove "nidmresults-examples" in examples filename

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#19]
**Is your feature request related to a problem? Please describe.**
The filenames in the `results` folder are too long and therefore the extension sometimes hidden (replaced by `...`) which make it difficult to parse the examples:

<img width="991" alt="Screenshot 2023-01-27 at 11 25 52" src="https://user-images.githubusercontent.com/5374264/215064277-69ee1690-f052-47eb-81ae-5aa6c29f4e49.png">

**Describe the solution you'd like**
Could we shorten the filenames to remove the `nidmresults-examples` prefix?

**Describe alternatives you've considered**
If there are other ideas to shorten filenames, those can be implemented at the same time :)

**Additional context**
This applies to both SPM and FSL examples

**Comment by thomasbtnfr** [comment]
The prefix `nidmresults-examples` has been removed in the branch `boutiques` for spm and fsl. Example [here](https://github.com/Inria-Empenn/BEP028_BIDSprov/tree/boutiques/results/fsl).
