### ISSUE TITLE
Digest Attribute

### ISSUE THREAD

**Issue by hermann74** [Inria-Empenn/BEP028_BIDSprov#2]
# FROM Specification

  RECOMMENDED. Dict. For files, this would include checksums of files. It would take the form ```{"<checksum-name>": "value"}```

# Actuellement
-  pour les entités entrantes (1 fichier par entité) : cf [code](https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/6ba857c709bc5447a366bd9ca16b321341809e67/bids_prov/spm_parser.py#L78)
**pourquoi un dictionnaire pour plusieurs fichiers dans la spec?**
-  checksum-name = "sha256"+entity[@id] , **bon ?** 

# Exemple
```jsonld

"prov:Entity": [
      {
        "@id": "niiri:zzX6hqo35uwZqxZOOHjk",
        "label": "my_files_sub-01_task-tonecounting_bold.nii.gz",
        "prov:atLocation": "/my_files/sub-01_task-tonecounting_bold.nii.gz",
        "digest": { "sha256_niiri:zzX6hqo35uwZqxZOOHjk": 
        "e14eaba2b2f48a040d85da4abf9a1f62e27c710c16d770ea81b4904ee160c54e"
        }
```

# Problem:
problème d'accès au fichier (cf [issue](https://github.com/Inria-Empenn/BEP028_BIDSprov/issues/1#issue-1499942031) )
pour effectuer le checksum. Pour l'exemple, faux fichier texte créé avec un chemin relatif au batch.m (input)
@cmaumet

**Comment by cyril-data** [comment]
J'ai ajouté un test sur **digest** dans ce [code](https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/d4c4d83dd018697843bda59099f7fb87152062f0/bids_prov/tests/test_spm_parser.py#L105). 

Il sera à modifier lorsqu'on aura statué sur les chemins relatifs (cf [issue](https://github.com/Inria-Empenn/BEP028_BIDSprov/issues/1#issue-1499942031) ) et cette issue.

**Comment by thomasbtnfr** [comment]
This issue is linked to this PR : https://github.com/bids-standard/BEP028_BIDSprov/pull/103. I close it.
