### ISSUE TITLE
[Bug]: Some extra activities should be deleted

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#20]
### batch name and line

Checking [this example](https://github.com/bids-standard/BEP028_BIDSprov/blob/master/results/fsl/nidmresults-examples_fsl_con_f_multiple_report_log.jsonld#L1650), we have an activity with label `stats___numTS=38352`.

I was not sure what Command would correspond to this and in fact when looking in the corresponding log file for `numTS` I found: 

```
Log directory is: stats paradigm.getDesignMatrix().Nrows()=104 paradigm.getDesignMatrix().Ncols()=2 sizeTS=104 numTS=38352 Calculating residuals... Completed Estimating residual autocorrelation... Calculating raw AutoCorrs... Completed mode = 9979.81 sig = 963 Spatially smoothing auto corr estimates ......... Completed Tukey M = 10 Tukey estimates... Completed Completed Prewhitening and Computing PEs... Percentage done: 
```

This is a message displayed in the Terminal and should be ignored when parsing the log file (and therefore the corresponding activity should not be created). I think this is True in other places as well, see for example https://github.com/bids-standard/BEP028_BIDSprov/blob/master/results/fsl/nidmresults-examples_fsl_con_f_multiple_report_log.jsonld#L1641-L1646.

### What happened?

Extra (erroneous) activities are currently created by the FSL parser.

### Describe the expected ground-truth ?

Remove the erroneous activities :)

### What soft is concerned

FSL

**Comment by thomasbtnfr** [comment]
This problem has been fixed in the `boutiques` branch. Example [here](https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/boutiques/results/fsl/fsl_con_f_multiple_report_log.jsonld). To be used, a command must be preceded by a line break now
