### ISSUE TITLE
[Bug]: One activity per command in the logs

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#21]
### batch name and line

The parsing of the log files in FSL seems to be broken. In practice we should have an Activity created for each command in the logs.

For examples, in https://github.com/bids-standard/BEP028_BIDSprov/blob/master/results/fsl/nidmresults-examples_fsl_con_f_multiple_report_log.jsonld#L2870-L2872 , `pngappend` is an Entity, 

But in the log we have:
```
/usr/local/packages/fsl-5.0.8/bin/pngappend sla.png + slb.png + slc.png + sld.png + sle.png + slf.png + slg.png + slh.png + sli.png + slj.png + slk.png + sll.png example_func2highres1.png ; /usr/local/packages/fsl-5.0.8/bin/slicer highres example_func2highres -s 2 -x 0.35 sla.png -x 0.45 slb.png -x 0.55 slc.png -x 0.65 sld.png -y 0.35 sle.png -y 0.45 slf.png -y 0.55 slg.png -y 0.65 slh.png -z 0.35 sli.png -z 0.45 slj.png -z 0.55 slk.png -z 0.65 sll.png ;
```
which means that `pngappend` is a Command and should instead be defined as an Activity.

This problem is likely to impact other Activities as well. I think that the main logic of the parsing of the log files might be in question here.

### What soft is concerned

FSL

**Comment by thomasbtnfr** [comment]
I'm not sure if this bug is still present. I checked the jsonld obtained for `fsl_conf_f_multiple` and `pngappend` always appears (9 times in registration section) as an activity. I checked for other files that the number of activities was equal to the number of commands. Can you confirm @cmaumet that this bug is no longer present?

**Comment by cmaumet** [comment]
@thomasbtnfr yes I think this is good now. Thanks!
