### ISSUE TITLE
All examples in a single parent directory

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#22]
**Is your feature request related to a problem? Please describe.**
Currently we have examples in https://github.com/Inria-Empenn/BEP028_BIDSprov/tree/master/examples and in https://github.com/Inria-Empenn/BEP028_BIDSprov/tree/master/results

**Describe the solution you'd like**
It would be easier to have a single parent directory with all examples inside, something like:
```
|__ examples
|____ fsl_default
|____ spm_default
|____ fmriprep
|____ fsl
|____ spm
```

**Describe alternatives you've considered**
If this ends up being too complicate (e.g. if we need one folder for the github action with nothing inside), we could alternatively do something like: 
```
|__ examples
|____ fsl_default
|____ spm_default
|____ fmriprep
|____ from_parsers # This would be the equivalent of current "results" folder
|______ fsl
|______ spm
```

**Additional context**
Note that the `fsl_default` and `spm_default` directories are meant to be removed soon but I would keep them for now (until we are confident that the SPM and FSL exporters can be directly used to export those -- we have a few bugs to fix before this can be done :) ).

**Comment by thomasbtnfr** [comment]
The alternative solution has been implemented in the `boutiques` branch.
See : [https://github.com/Inria-Empenn/BEP028_BIDSprov/tree/boutiques/examples](https://github.com/Inria-Empenn/BEP028_BIDSprov/tree/boutiques/examples)
