### ISSUE TITLE
Remove hierarchies of Activities in FSL

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#26]
**Is your feature request related to a problem? Please describe.**
Currently, the FSL parser proceeds by creating multiple levels of activities that are connected together using `wasInfluencedBy`relationships. See for example: https://github.com/bids-standard/BEP028_BIDSprov/blob/master/examples/from_parsers/fsl/fsl_default_report_log.jsonld#L16-L20.

While this might be something  compatible with the BIDS-Prov spec, it is quite different from what we've done for SPM and it creates an extra level of complexity in the graphs.

**Describe the solution you'd like**
Is it feasible to comment out the creation of the extra Activities (i.e. those that do not correspond to a command in the logs)?

**Describe alternatives you've considered**
None

**Comment by thomasbtnfr** [comment]
I did it on the `extra-activities` branch. This is how it looks for [fsl_default](https://raw.githubusercontent.com/Inria-Empenn/BEP028_BIDSprov/extra-activities/examples/from_parsers/fsl/fsl_default_report_log.png).  
 I noticed that there was also the keyword `derivedFrom` used in commands like `cp f1 f2` where f2 is derived from f1. Should we keep this keyword which is not present in SPM?

**Comment by cmaumet** [comment]
+1 to remove `wasDerivedFrom`

**Comment by cmaumet** [comment]
I beleive this was merged as part of: https://github.com/bids-standard/BEP028_BIDSprov/pull/93 ?

**Comment by thomasbtnfr** [comment]
Yes this one is solved ! I close it.
