### ISSUE TITLE
FSL : fslroi

### ISSUE THREAD

**Issue by thomasbtnfr** [Inria-Empenn/BEP028_BIDSprov#27]
**Is your feature request related to a problem? Please describe.**
The logs of the `fslroi` function are not obvious. For example, we have the following log: `/usr/local/packages/fsl-5.0.8/bin/fslroi prefiltered_func_data example_func 52 1`. 
`prefiltered_func_data` seems to be the input entity (= used).
`example_func` seems to be the generated entity but what about `52` and `1` ? These are attributes but what are their associated parameter names?

Currently these two parameters are not taken into account. fslroi is modelled like this in BIDS-prov:
![image](https://user-images.githubusercontent.com/115700860/216547879-f9e40532-1d30-43d3-b991-100331b49ed4.png)

 and this is perhaps the best option? What do you think @cmaumet?

**Comment by cmaumet** [comment]
@thomasbtnfr: agreed! for `fslroi` (and for all commands in FSL), for now I think we can start by:
 1. storing the command in the `Command` attribute (I beleive this is already done)
 2. ignoring the `Parameters` attribute (which is OPTIONAL) until we have a good strategy on how to store a command line (this is related to https://github.com/Inria-Empenn/BEP028_BIDSprov/issues/17#issuecomment-1413339330 in which `Parameters` was called `attributes`
 3.  having a strategy to handle input/outputs (using a yml file?) and I can help filling those in to specify which part of the command is used/generatedBy.
 
 How do you feel about this?

**Comment by thomasbtnfr** [comment]
For the config file, it suits me fine. I just have a doubt. 

If you have for example the `fslroi` function which is used in one case like this: 
`/usr/local/packages/fsl-5.0.8/bin/fslroi prefiltered_func_data example_func 52 1` 
and in another case like this:
`/usr/local/packages/fsl-5.0.8/bin/fslroi -in prefiltered_func_data -out example_func 52 1`,
How do we write this configuration file? The first time by saying that `used` matches the first argument and the second time by saying that `used` matches `-in`. I don't know if this happens, I'd have to explore the example files.

**Comment by cmaumet** [comment]
@thomasbtnfr -- my take on this (I might be wrong) is that this should not happen (unless we have multiple versions of `fslroi` in use).

**Comment by cmaumet** [comment]
@thomasbtnfr - are we good on this following our last discussion or is there more input needed from me? Thanks!

**Comment by thomasbtnfr** [comment]
This is clear to me. Do we keep this issue open? (if so, we would have to open an issue for many commands)

**Comment by cmaumet** [comment]
I think we can close this one :)
