### ISSUE TITLE
FSL naming of activities

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#29]
**Is your feature request related to a problem? Please describe.**
Currently activities in FSL are named with something like `<NAME_OF_HEADING>_<COMMAND_NAME>` for example: 
```
"label": "initialisation_fslmaths"
```
in https://github.com/bids-standard/BEP028_BIDSprov/blob/610fd46a8bcb57989f7fac9d65ca2c31398a7750/examples/from_parsers/fsl/fsl_default_report_log.jsonld#L18

**Describe the solution you'd like**
Instead, it would be great if we could take an approach similar to what we have done in SPM:
 1. always use the command alone as label, in the example above we would have
```
"label": "fslmaths"
```

 2. provide developers with a way to give a mapping to have a more explicit name (similar as https://github.com/bids-standard/BEP028_BIDSprov/blob/ea7c8e56166ee696317e29d96b7f5a23b947d6f4/bids_prov/spm/spm_labels.json)

**Describe alternatives you've considered**
No alternative considered but happy to hear your thoughts!

**Additional context**
Two separate pull requests would be great for this (one to use the command only and a second one to implement the name mapping)

**Comment by thomasbtnfr** [comment]
I can remove <NAME_OF_HEADING>_. For the mapping file, it had already been done. We have a similar [file](https://github.com/bids-standard/BEP028_BIDSprov/blob/ea7c8e56166ee696317e29d96b7f5a23b947d6f4/bids_prov/fsl/fsl_labels.json) to the one in SPM. Here is an example with mkdir already working : https://github.com/bids-standard/BEP028_BIDSprov/blob/610fd46a8bcb57989f7fac9d65ca2c31398a7750/examples/from_parsers/fsl/fsl_default_report_log.jsonld#L45

**Comment by cmaumet** [comment]
Even better :) If you can implement 1. then that would be perfect!
