### ISSUE TITLE
Command [REQUIRED]

### ISSUE THREAD

**Issue by cyril-data** [Inria-Empenn/BEP028_BIDSprov#3]
Dans le [doc](https://docs.google.com/document/d/1vw3VNDof5cecv2PkFp7Lw_pNUTUo8-m8V4SIdtGJVKs/edit#heading=h.h15lzmuljsky), il est spécifié qu'il faut une clé-valeur **Command**   : 

<h2 dir="ltr" style="line-height:1.2;text-align: justify;margin-top:18pt;margin-bottom:4pt;" id="docs-internal-guid-49a06f2a-7fff-41ad-f9fb-090528a1489c"><span style="font-size:13pt;font-family:'Trebuchet MS';color:#222222;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2.1 Activity</span></h2><p dir="ltr" style="line-height:1.2;text-align: justify;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:11pt;font-family:Arial;color:#222222;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Each Activity record has the following fields:</span></p><div dir="ltr" style="margin-left:0.75pt;" align="left">
<div dir="ltr" style="margin-left:0.75pt;" align="left" id="docs-internal-guid-567e69ad-7fff-b7e9-a029-6e61bc300323">

Key name | Description
-- | --
@id | REQUIRED. Unique URIs (for example a UUID). Identifier for the  activity.
Label | REQUIRED. String. Name of the tool used (e.g. “bet”).
**Command** | **REQUIRED**. String. Command used to run the tool.

</div>

Faut en ajouter une ? Si oui, laquelle ? @cmaumet

**Comment by thomasbtnfr** [comment]
The `Command` field has been added for all 3 parsers (SPM, FSL, AFNI).
