### ISSUE TITLE
[Bug]: fslmaths

### ISSUE THREAD

**Issue by cyril-data** [Inria-Empenn/BEP028_BIDSprov#34]
### batch name and line

For the command [/usr/local/fsl/bin/fslmaths /Users/cmaumet/Data/fsl_practicals/fsl_course_data/fmri/fmri_fluency/fmri prefiltered_func_data -odt float](https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/1d757dc1b962628473a5e4d0f52562faabc099a2/examples/from_parsers/fsl/fsl_full_examples001_report_log.html#L52)

### What happened?

A bug happened!

fslmaths should get as input *fmri* and output *prefiltered_func_data* but it is not the case because there is no output from fslmaths : 

![image](https://user-images.githubusercontent.com/56917204/222365392-ac4eb6d7-2c12-4527-a513-cfbecb1b6aea.png)

### Describe the expected ground-truth ?

The expected ground-truth : 

![image](https://user-images.githubusercontent.com/56917204/222367547-3f12639e-2756-405a-8576-ec2cb7e405a1.png)

### What soft is concerned

FSL

**Comment by thomasbtnfr** [comment]
Perhaps this issue might interest you: #30

**Comment by cyril-data** [comment]
Indeed, sorry for the repetition. I continue the conversation in : https://github.com/Inria-Empenn/BEP028_BIDSprov/issues/30
