### ISSUE TITLE
Add back manual examples

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#35]
Hi @cyril-data @hermann74 -- the manual examples were lost  [in the AFNI PR (see this comment)](https://github.com/bids-standard/BEP028_BIDSprov/pull/97#issuecomment-1453149948). Can you revert the commit that introduced this change to add them back? Thanks!

**Comment by hermann74** [comment]
Hi, i just readd examples in this commit https://github.com/Inria-Empenn/BEP028_BIDSprov/commit/9831636305c16db39bfd29afc6be10585933d48b on branch dev_afni (currently push in PR #99 )
