### ISSUE TITLE
[FSL] change signature of get_kwarg and 

### ISSUE THREAD

**Issue by hermann74** [Inria-Empenn/BEP028_BIDSprov#36]
**Is your feature request related to a problem? Please describe.**

https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/34fbc5b1eb0df030ad9f6065669dfd2a893a4293/bids_prov/fsl/fsl_parser.py#L265
        `parser, inputs_kwarg = _get_kwarg(parser, parameters["used"])`
It's less readable to return  a modified version of  parameter `parser` 

**Describe the solution you'd like**

```python
def _get_kwarg(parser, serie,  with_value=True):
    arg_list = []
    for u_arg in serie:
        if type(u_arg) == dict:
            parser.add_argument(u_arg["name"], nargs='+', action='append')
            arg_list.append((u_arg["name"], [u_arg["index"]]))
        if type(u_arg) == str and ":" not in u_arg:
            if with_value:
                parser.add_argument(u_arg)
                arg_list.append((u_arg, [0]))
            else:
                parser.add_argument(u_arg, action='store_true')
                arg_list.append((u_arg, []))

    return parser
```
Another solution is to return add_argument_list and to add them outside. In such casen parser is not a parameter ...

**Comment by cyril-data** [comment]
FIX in commit [answer hermann ](https://github.com/bids-standard/BEP028_BIDSprov/pull/98/commits/f0c82cd202e73f45f141ec14072d28e5a5850308)
