### ISSUE TITLE
[BUG] huge git history because of png pushed at every commit

### ISSUE THREAD

**Issue by hermann74** [Inria-Empenn/BEP028_BIDSprov#37]
**Is your feature request related to a problem? Please describe.**
this github repository weight more than 5 Go !! in local repository in directory  `.git/objects/pack`  
As Nidm-example pngs (~60 Mo)  are pushed in github repository at every commits. Therefore, git history has grown !

**Describe the solution you'd like**
Perhaps reuse artefact ....

**Others solutions to inspect**
- https://gitbetter.substack.com/p/how-to-clean-up-the-git-repo-and
- https://panjeh.medium.com/cleaning-up-git-github-repository-without-deleting-git-directory-c86b7415b51b

**Comment by thomasbtnfr** [comment]
The following solution has been implemented : https://github.com/bids-standard/BEP028_BIDSprov/pull/104
Perhaps a `rebase` will be needed to clean up the history of images and json-ld previously accumulated before this solution.
