### ISSUE TITLE
Update contributor's list

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#38]
Hi @cyril-data @hermann74 and @thomasbtnfr! Your name should really be on the contributor's list at: https://github.com/bids-standard/BEP028_BIDSprov#who-is-building-bep-028 

Can you update the README to add your names?

In addition, it would be great to use emoji's as in https://github.com/bids-standard/bids-starter-kit#contributors- , can you add this as well?

Thanks!

**Comment by thomasbtnfr** [comment]
Done in this PR : https://github.com/bids-standard/BEP028_BIDSprov/pull/101
