### ISSUE TITLE
[Bug]: Replace all niiri by urn

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#6]
### batch name and line

In all identifiers for which `niiri` is used as a prefix.

For example here: https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/master/results/nidmresults-examples_spm_2_t_test_batch.jsonld#L26 

### What happened?

the prefix `niiri:` is used for the identifier : `"@id": "niiri:cfg_basicio.file_dir.file_ops.file_move._1gWIqVrGmQZ"`.

### Describe the expected ground-truth ?

We have now decided (more context in https://github.com/bids-standard/BEP028_BIDSprov/issues/69) that we no longer will use `niiri` as a prefix and therefore those should be replaced by `urn`.

### What soft is concerned

SPM

**Comment by thomasbtnfr** [comment]
In the "spm_fsl_exporter" branch, the prefix `niiri` has been replaced by `urn`.
