### ISSUE TITLE
[Bug]: Remove project info

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#8]
### batch name and line

Hard-coded information about the project that is found at the top of each example should be deleted. 

For example here: https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/master/results/nidmresults-examples_spm_2_t_test_batch.jsonld#L5-L12

### What happened?

This info
```
  "wasGeneratedBy": {
    "@id": "INRIA",
    "@type": "Project",
    "wasAssociatedWith": {
      "@id": "NIH",
      "@type": "Organization",
      "hadRole": "Funding"
    }
```
should be removed

### Describe the expected ground-truth ?

The expected ground-truth : <empty>

### What soft is concerned

SPM

**Comment by thomasbtnfr** [comment]
Removed in the "spm_fsl_exporter" branch
