### ISSUE TITLE
[Bug]: Identifier for the agent should be a uuid

### ISSUE THREAD

**Issue by cmaumet** [Inria-Empenn/BEP028_BIDSprov#9]
### batch name and line

Currently the identifier of the agent is hard-coded to be `exampleAgentID`

for example here: https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/master/results/nidmresults-examples_spm_2_t_test_batch.jsonld#L17  

this should be removed by a UUID (as for any activity/entity)

### What happened?

Identifier of the agent is currently: `"@id": "exampleAgentID"`...

### Describe the expected ground-truth ?

... but should look like: 

`"@id": "urn:08f5a59a47f33372cedc55d11fc67e1a"`

Note that beyond the definition, this identifier should then be reused each time an activity has a `wasAssociatedWith`relation to the agent. 

For example in https://github.com/Inria-Empenn/BEP028_BIDSprov/blob/master/results/nidmresults-examples_spm_2_t_test_batch.jsonld#L31, instead of `"wasAssociatedWith": "RRID:SCR_007037"`we should have `"wasAssociatedWith": "urn:08f5a59a47f33372cedc55d11fc67e1a"`

### What soft is concerned

SPM

**Comment by thomasbtnfr** [comment]
Fixed in the spm_fsl_exporter branch
